services:

  nginx:
    build: ./nginx
    container_name: t_nginx
    ports:
      - "443:443"
    env_file:
      - .env
    depends_on:
      frontend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network

  frontend: 
    build: ./frontend
    container_name: t_frontend
    expose:
      - "${FRONTEND_PORT}"  # Expose internally, not to host
    env_file:
      - .env
    # environment:
    #   - PORT=${FRONTEND_PORT}
    #   - VITE_API_URL=/api
    healthcheck:
        test: ["CMD", "test", "-f", "/tmp/frontend-ready"]
        # test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://172.18.0.2:${FRONTEND_PORT}"]
        interval: 5s
        timeout: 3s
        retries: 10
        start_period: 30s  # Give init.sh time to run
    volumes:
      - frontend_app:/app:nocopy
      # - /app/node_modules # prevent node_module being overwritten by host
    networks:
      - app-network
  
  # backend:
  #   build:
  #     context: ./dev/backend
  #     dockerfile: Dockerfile
  #     container_name: t_backend
  #     expose:
  #     - "${BACKENDEND_PORT}"  # Expose internally, not to host
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:${BACKENDEND_PORT}/health"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 40s  # Give your app time to start
  #   networks:
  #     - app-network

  # database:


volumes:
  frontend_app:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/frontend
      o: bind

  backend_app:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/backend
      o: bind

  # database:


networks:
  app-network:
    driver: bridge