services:

  nginx:
    build: ./${SERV_DIR}/nginx
    container_name: t_nginx
    ports:
      - "443:443"
    env_file:
      - .env
    depends_on:
      frontend:
        condition: service_healthy
    # restart: unless-stopped
    networks:
      - app-network

  frontend: 
    build: ./${SERV_DIR}/frontend
    init: true
    container_name: t_frontend
    expose:
      - "${FRONTEND_PORT}"  # Expose internally, not to host
    env_file:
      - .env
    healthcheck:
        # test: ["CMD", "curl", "-f", "http://localhost:${FRONTEND_PORT}"]
        test: ["CMD", "test", "-f", "/tmp/frontend-ready"]
        interval: 5s
        timeout: 3s
        retries: 10
        start_period: 30s  # Give init.sh time to run
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - frontend_app:/app:nocopy
    # restart: unless-stopped
    networks:
      - app-network
  
  backend:
    build: ./${SERV_DIR}/backend
    init: true
    container_name: t_backend
    expose:
      - "${BACKEND_PORT}"  # Expose internally, not to host
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "test", "-f", "/tmp/backend-ready"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s  # Give your app time to start
    secrets:
      - livekit_api_key
      - livekit_api_secret
    depends_on:
      - livekit
    volumes:
      - backend_app:/app:nocopy
    # restart: unless-stopped
    networks:
      - app-network

  livekit:
    build: ./${SERV_DIR}/livekit
    init: true
    container_name: t_livekit
    ports:
      - "7881:7881"
      - "7882:7882/udp"
      # - "50000-50010:50010-50010/udp"
      - "${LIVEKIT_UDP_START}-${LIVEKIT_UDP_END}:${LIVEKIT_UDP_START}-${LIVEKIT_UDP_END}/udp"
    env_file:
      - .env
    secrets:
      - livekit_api_key
      - livekit_api_secret
      - redis_pwd
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app-network

  redis:
    build: ./${SERV_DIR}/redis
    init: true
    container_name: t_redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 5s
    networks:
      - app-network
    secrets:
      - redis_pwd
    volumes:
      - redis:/data:nocopy



volumes:
  frontend_app:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/dev/data/frontend
      o: bind

  backend_app:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/dev/data/backend
      o: bind

  database:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/dev/data/database
      o: bind

  redis:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/dev/data/redis
      o: bind


networks:
  app-network:
    driver: bridge


secrets:
  livekit_api_key:
    file: ./secrets/livekit_api_key.txt
  livekit_api_secret:
    file: ./secrets/livekit_api_secret.txt
  redis_pwd:
    file: ./secrets/redis_password.txt