import { ModalHeader } from "@/shared";
import { useMemo } from "react";

type Summary = {
  mainDiscussionPoints: string[];
  decisionsMade: string[];
  actionItems: string[];
  importantDeadlines: string[];
};

type Props = {
  summary: string | null;
  summaryStatus: "pending" | "completed" | "failed";
  onClose: () => void;
};

function SummarySection({
  title,
  items,
}: {
  title: string;
  items: string[];
}) {
  return (
    <div className="flex flex-col gap-y-2 mb-2">
      <h3 className="text-base font-semibold text-white">{title}</h3>

      {items.length > 0 ? (
        <ul className="list-disc list-inside space-y-1 text-sm text-foreground-3">
          {items.map((item, index) => (
            <li key={index}>{item}</li>
          ))}
        </ul>
      ) : (
        <p className="text-sm italic text-gray-500">
          No items.
        </p>
      )}
    </div>
  );
}

export function SummaryModal({
  summary,
  summaryStatus,
  onClose,
}: Props) {
  const parsedSummary = useMemo<Summary | null>(() => {
    if (!summary || summaryStatus !== "completed") {
      return null;
    }

    try {
      return JSON.parse(summary) as Summary;
    } catch (error) {
      console.error("Failed to parse summary:", error);
      return null;
    }
  }, [summary, summaryStatus]);

  return (
      <div className="form-layout">

        {/* Header */}
        <ModalHeader 
            title='Meeting Summary'
            onClose={onClose}
        />
        <div className="mb-2"/>

        {/* Pending */}
        {summaryStatus === "pending" && (
          <div className="py-8 text-center text-foreground-3">
            Generating meeting summary...
          </div>
        )}

        {/* Failed */}
        {summaryStatus === "failed" && (
          <div className="py-8 text-center text-danger">
            Failed to generate meeting summary.
          </div>
        )}

        {/* Completed */}
        {summaryStatus === "completed" && parsedSummary && (
          <>
            <SummarySection
              title="Main Discussion Points"
              items={parsedSummary.mainDiscussionPoints}
            />

            <SummarySection
              title="Decisions Made"
              items={parsedSummary.decisionsMade}
            />

            <SummarySection
              title="Action Items"
              items={parsedSummary.actionItems}
            />

            <SummarySection
              title="Important Deadlines"
              items={parsedSummary.importantDeadlines}
            />
          </>
        )}

        {/* Completed but parsing failed */}
        {summaryStatus === "completed" && !parsedSummary && (
          <div className="py-8 text-center text-foreground-3">
            No summary available.
          </div>
        )}

        {/* AI Disclaimer */}
        <div className="mt-2 border-t border-[#2d2d2d] pt-4 text-xs text-gray-500">
        ✨ This meeting summary was generated by Google AI.
        </div>
      </div>
  );
}