import { useMemo } from "react";

type Summary = {
  mainDiscussionPoints: string[];
  decisionsMade: string[];
  actionItems: string[];
  importantDeadlines: string[];
};

type Props = {
  summary: string | null;
  summaryStatus: "pending" | "completed" | "failed";
  onClose: () => void;
};

function SummarySection({
  title,
  items,
}: {
  title: string;
  items: string[];
}) {
  return (
    <div className="flex flex-col gap-y-2">
      <h3 className="text-base font-semibold text-white">{title}</h3>

      {items.length > 0 ? (
        <ul className="list-disc list-inside space-y-1 text-sm text-gray-300">
          {items.map((item, index) => (
            <li key={index}>{item}</li>
          ))}
        </ul>
      ) : (
        <p className="text-sm italic text-gray-500">
          No items.
        </p>
      )}
    </div>
  );
}

export function SummaryModal({
  summary,
  summaryStatus,
  onClose,
}: Props) {
  const parsedSummary = useMemo<Summary | null>(() => {
    if (!summary || summaryStatus !== "completed") {
      return null;
    }

    try {
      return JSON.parse(summary) as Summary;
    } catch (error) {
      console.error("Failed to parse summary:", error);
      return null;
    }
  }, [summary, summaryStatus]);

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-sm">
      <div className="flex flex-col gap-y-6 w-full max-w-[480px] max-h-[88vh] overflow-y-auto rounded-[1.5rem] bg-[#1b1b1b] border border-[#242424] px-8 py-7 shadow-2xl text-gray-200">

        {/* Header */}
        <div className="flex items-center justify-between">
          <h2 className="text-2xl font-bold">
            Meeting Summary
          </h2>

          <button
            onClick={onClose}
            className="rounded-full p-2 text-gray-400 transition hover:bg-[#2b2b2b] hover:text-white"
          >
            ✕
          </button>
        </div>

        {/* Pending */}
        {summaryStatus === "pending" && (
          <div className="py-8 text-center text-gray-400">
            Generating meeting summary...
          </div>
        )}

        {/* Failed */}
        {summaryStatus === "failed" && (
          <div className="py-8 text-center text-red-400">
            Failed to generate meeting summary.
          </div>
        )}

        {/* Completed */}
        {summaryStatus === "completed" && parsedSummary && (
          <>
            <SummarySection
              title="Main Discussion Points"
              items={parsedSummary.mainDiscussionPoints}
            />

            <SummarySection
              title="Decisions Made"
              items={parsedSummary.decisionsMade}
            />

            <SummarySection
              title="Action Items"
              items={parsedSummary.actionItems}
            />

            <SummarySection
              title="Important Deadlines"
              items={parsedSummary.importantDeadlines}
            />
          </>
        )}

        {/* Completed but parsing failed */}
        {summaryStatus === "completed" && !parsedSummary && (
          <div className="py-8 text-center text-gray-400">
            No summary available.
          </div>
        )}

        {/* AI Disclaimer */}
        <div className="mt-2 border-t border-[#2d2d2d] pt-4 text-xs text-gray-500">
        ✨ This meeting summary was generated by Google AI.
        </div>
      </div>
    </div>
  );
}