# this version uses set,
# container ip address is dynamically solved on start
# ideal for development env where frequent docker start/stop
# but will have performance overhead since keep dynamically resolve

user nginx;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    resolver 127.0.0.11 valid=10s;
    resolver_timeout 5s;

    server {
        listen 443 ssl;
        listen [::]:443 ssl;

        server_name ${DOMAIN_NAME} localhost;

        ssl_protocols       TLSv1.2 TLSv1.3;
        ssl_certificate     /etc/nginx/ssl/${DOMAIN_NAME}.crt;
        ssl_certificate_key /etc/nginx/ssl/${DOMAIN_NAME}.key;
        ssl_ciphers         HIGH:!aNULL:!MD5;

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        location /api/ {
            set $backend_upstream "backend:${BACKEND_PORT}";
            proxy_pass http://$backend_upstream; 
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            set $frontend_upstream "frontend:${FRONTEND_PORT}";
            proxy_pass http://$frontend_upstream;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            
            proxy_connect_timeout 60s;
            proxy_send_timeout 60s;
            proxy_read_timeout 60s;
        }

        autoindex off;
    }
}